#!/bin/bash

MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=root
MONGO_INITDB_DATABASE=cv
MONGO_PORT=27017

docker run --rm --name xml_mongo -d \
		-e MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME \
		-e MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD \
		-e MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE \
		-p $MONGO_PORT:27017 \
		mongo
